services:
  gerente_agent:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      GERENTE_AGENT_URL: http://gerente_agent:8000
      PESQUISADOR_AGENT_URL: http://pesquisador_agent:8000
      REDATOR_AGENT_URL: http://redator_agent:8000
    deploy:
      replicas: 1
    networks:
      - agents_network
    ports:
      - "8000:8000"

  pesquisador_agent:
    build: 
      context: .
      dockerfile: ./agents/pesquisador_agent/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      AGENT_PUBLIC_URL: http://localhost:8001
    deploy:
      replicas: 1
    networks:
      - agents_network
    ports:
      - "8001:8000"

  redator_agent:
    build: 
      context: .
      dockerfile: ./agents/redator_agent/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      AGENT_PUBLIC_URL: http://localhost:8002
    deploy:
      replicas: 1
    networks:
      - agents_network
    ports:
      - "8002:8000"
networks:
  agents_network:
    external: true
